"""CLI package for Todo Agent."""

from .app import (
    run_cli,
    run_cli_async,
    handle_command,
    run_interactive_selection_menu,
    run_interactive_checkbox_menu,
    get_terminal_width,
    get_terminal_height,
    display_width,
    truncate_to_width,
    pad_to_width,
    build_box_header,
    build_box_footer,
    is_compact_terminal,
    strip_ansi,
    fit_box_line,
    show_help,
    select_mode_interactive,
    apply_mode_switch,
    MODE_OPTIONS,
)
from .components import SlashCommandCompleter

__all__ = [
    "run_cli",
    "run_cli_async",
    "handle_command",
    "run_interactive_selection_menu",
    "run_interactive_checkbox_menu",
    "SlashCommandCompleter",
    "MODE_OPTIONS",
    "select_mode_interactive",
    "apply_mode_switch",
    "show_help",
    "get_terminal_width",
    "get_terminal_height",
    "display_width",
    "truncate_to_width",
    "pad_to_width",
    "build_box_header",
    "build_box_footer",
    "is_compact_terminal",
    "strip_ansi",
    "fit_box_line",
]
